# don't change
config-version: '${config_version}'

update-checker: true

# Requires server restart to apply changes.
hook:
  Nexo: true
  CraftEngine: true
  ItemsAdder: true
  CustomCrops: true
  CustomFishing: true
  CustomNameplates: true
  HMCCosmetics: true
  TypeWriter: true