# don't change
config-version: '${config_version}'

# General plugin settings
setting:
  # Check for plugin updates on startup
  update-checker: true

# Requires server restart to apply changes.
hook:
  Nexo: true
  CraftEngine: true
  ItemsAdder: true
  CustomCrops: true
  CustomFishing: true
  CustomNameplates: true
  HMCCosmetics: true
  CosmeticsCore: true
  TypeWriter: true
  WorldGuard: true
  CoinsEngine: true
  AdvancedEnchantments: true